name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    #   with:
    #     buildkitd-flags: --debug
    #     install: true
    #     driver-opts: network=host

    # - name: Create Buildx builder
    #   run: |
    #     docker buildx create --name mybuilder --use
    #     docker buildx inspect --bootstrap
    #     docker buildx ls

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_SECRET }}

    # - name: Build and push to Docker Hub
    #   uses: docker/build-push-action@v5
    #   with:
    #    context: .
    #    push: true
    #    platforms: linux/amd64,linux/arm64
    #    tags: apierson3/howagileairflow:latest

    # - name: Copy files to Raspberry Pi
    #   uses: appleboy/scp-action@v0.1.0
    #   with:
    #     host: ${{ secrets.DEPLOY_HOST }}  # Raspberry Pi IP address
    #     username: ${{ secrets.DEPLOY_USERNAME }} # Raspberry Pi username
    #     key: ${{ secrets.DEPLOY_PRIV_KEY }}  # Raspberry Pi SSH key
    #     password: ${{ secrets.DEPLOY_PASSWORD }}  # Raspberry Pi pw
    #     source: "deploy.tar"  # Source directory (current directory)
    #     target: "/home/apierson3/Desktop/how-agile-airflow" # Target directory on Raspberry Pi

    # test  2
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd ~/Desktop/how-agile-airflow/
          rm -rf raspberrypi_cicd
          git clone https://github.com/apierson3/raspberrypi_cicd.git
        timeout: 600s
        command_timeout: 300s


        # Copy to Pi
        #scp -r /home/runner/work/raspberrypi_cicd/raspberrypi_cicd/* ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:/home/apierson3/Desktop/how-agile-airflow


        # Run Airflow docker compose

        # docker compose up
        # Pull the latest image
        # docker pull apierson3/howagileairflow:latest
        
        # Stop and remove the container if it exists
        # docker stop howagile_airflow_container
        # docker rm howagile_airflow_container

        # Start the Airflow container in interactive mode and initialize the database
        #docker run --name init_airflow --entrypoint "/bin/bash" -d apierson3/howagileairflow:latest

        # Run the Airflow container
        # docker compose up apierson3/howagileairflow:latest
