name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
        install: true
        driver-opts: network=host

    - name: Create Buildx builder
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
        docker buildx ls

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       platforms: linux/amd64,linux/arm64
       tags: apierson3/howagileairflow:latest

    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          # Increase swap memory
          sudo fallocate -l 1G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

          # Pull the latest image
          docker pull apierson3/howagileairflow:latest
          
          # Stop and remove existing container if it exists
          docker stop howagile_airflow_container || true
          docker rm howagile_airflow_container || true

          # Start the Airflow container in interactive mode and initialize the database
          docker run --name init_airflow --entrypoint "/bin/bash" -d apierson3/howagileairflow:latest
          
          # Check if the container is running
          if docker ps | grep -q init_airflow; then
            # Initialize the database
            docker exec init_airflow airflow db init
          
            # Stop and remove the initialization container
            docker stop init_airflow
            docker rm init_airflow

            # Run the Airflow container
            docker run -d --platform linux/arm64 --name howagile_airflow_container -p 80:80 apierson3/howagileairflow:latest
          else
            echo "Failed to start init_airflow container"
            exit 1
          fi
