name: Deploy Python Script

on:
  push:
    branches:
      - '**'  # This specifies all branches
    paths:
      - '**'  # This specifies all files

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PI }}
    - name: Copy Python script to Raspberry Pi
      run: scp -r / apierson3@andrewpi:/home/apierson3/Documents/testcicd
